final List<Map<String, dynamic>> userList = [
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/3.jpg',
    'video': 'https://example.com/video1.mp4',
    'full_name': 'Julia Ann',
    'address': 'New York',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Maratha',
    'devak': 'Lotus',
    'ras': 'Leo',
    'gan': 'Dog',
    'phone_number': '1234567890',
    'education': 'B.Tech (CSE)',
    'demands': 'Looking for a well-settled partner',
    'job': 'Software Engineer',
    'height': '5\'6"',
    'about': 'A kind-hearted and ambitious individual.',
    'email': 'julia.ann@example.com',
    'fathers_name': 'Mr. Ann',
    'mothers_name': 'Mrs. Ann',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men1.jpg',
    'video': '',
    'full_name': 'John Doe',
    'address': 'San Francisco',
    'age': '28',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Oak Tree',
    'ras': 'Taurus',
    'gan': 'Elephant',
    'phone_number': '0987654321',
    'education': 'M.S. (Mechanical Engineering)',
    'demands': 'Looking for a well-settled partner',
    'job': 'Mechanical Engineer',
    'height': '6\'1"',
    'about': 'A determined and responsible individual.',
    'email': 'john.doe@example.com',
    'fathers_name': 'Mr. Doe',
    'mothers_name': 'Mrs. Doe',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/4.jpg',
    'video': 'https://example.com/video2.mp4',
    'full_name': 'Sophia Brown',
    'address': 'Los Angeles',
    'age': '25',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Sunni',
    'devak': 'Moon',
    'ras': 'Gemini',
    'gan': 'Horse',
    'phone_number': '2345678901',
    'education': 'B.A. (English)',
    'demands': 'Seeking a partner who values family',
    'job': 'Teacher',
    'height': '5\'4"',
    'about': 'A caring and family-oriented individual.',
    'email': 'sophia.brown@example.com',
    'fathers_name': 'Mr. Brown',
    'mothers_name': 'Mrs. Brown',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men4.jpg',
    'video': '',
    'full_name': 'Michael Smith',
    'address': 'Chicago',
    'age': '30',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Brahmin',
    'devak': 'Peepal Tree',
    'ras': 'Aries',
    'gan': 'Lion',
    'phone_number': '3456789012',
    'education': 'PhD (Physics)',
    'demands': '',
    'job': 'Physicist',
    'height': '5\'9"',
    'about': 'A highly intellectual and curious person.',
    'email': 'michael.smith@example.com',
    'fathers_name': 'Mr. Smith',
    'mothers_name': 'Mrs. Smith',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Emma Johnson',
    'address': 'Houston',
    'age': '24',
    'gender': 'female',
    'cast': 'Christian',
    'sub_cast': 'Protestant',
    'devak': 'Rose',
    'ras': 'Cancer',
    'gan': 'Swan',
    'phone_number': '4567890123',
    'education': 'B.Sc (Biology)',
    'demands': 'Prefers a partner who loves nature',
    'job': 'Biologist',
    'height': '5\'5"',
    'about': 'An environmentally conscious person.',
    'email': 'emma.johnson@example.com',
    'fathers_name': 'Mr. Johnson',
    'mothers_name': 'Mrs. Johnson',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video3.mp4',
    'full_name': 'Ava Williams',
    'address': 'Phoenix',
    'age': '27',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Vaishya',
    'devak': 'Sunflower',
    'ras': 'Leo',
    'gan': 'Tiger',
    'phone_number': '5678901234',
    'education': 'MBA',
    'demands': '',
    'job': 'Marketing Manager',
    'height': '5\'7"',
    'about': 'A confident and goal-driven person.',
    'email': 'ava.williams@example.com',
    'fathers_name': 'Mr. Williams',
    'mothers_name': 'Mrs. Williams',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'James Wilson',
    'address': 'Philadelphia',
    'age': '29',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Kshatriya',
    'devak': 'Lion',
    'ras': 'Virgo',
    'gan': 'Elephant',
    'phone_number': '6789012345',
    'education': 'B.Tech (Civil Engineering)',
    'demands': '',
    'job': 'Civil Engineer',
    'height': '6\'0"',
    'about': 'A hardworking and focused individual.',
    'email': 'james.wilson@example.com',
    'fathers_name': 'Mr. Wilson',
    'mothers_name': 'Mrs. Wilson',
    'family_type': 'Joint family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video4.mp4',
    'full_name': 'Isabella Martinez',
    'address': 'San Antonio',
    'age': '23',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Shia',
    'devak': 'Star',
    'ras': 'Libra',
    'gan': 'Peacock',
    'phone_number': '7890123456',
    'education': 'BBA',
    'demands': 'Looking for a partner who is understanding',
    'job': 'Business Analyst',
    'height': '5\'3"',
    'about': 'A strategic thinker and compassionate person.',
    'email': 'isabella.martinez@example.com',
    'fathers_name': 'Mr. Martinez',
    'mothers_name': 'Mrs. Martinez',
    'family_type': 'Nuclear family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Elijah Anderson',
    'address': 'San Diego',
    'age': '26',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Olive Tree',
    'ras': 'Scorpio',
    'gan': 'Bear',
    'phone_number': '8901234567',
    'education': 'M.S. (Computer Science)',
    'demands': 'Open to relocating for the right partner',
    'job': 'Software Developer',
    'height': '5\'10"',
    'about': 'An adventurous and tech-savvy individual.',
    'email': 'elijah.anderson@example.com',
    'fathers_name': 'Mr. Anderson',
    'mothers_name': 'Mrs. Anderson',
    'family_type': 'Joint family',
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/2.jpeg",
    "video": "",
    "full_name": "Sita Patil",
    "address": "Nagpur",
    "age": "25",
    "gender": "female",
    "cast": "Hindu",
    "sub_cast": "Kshatriya",
    "devak": "Banana Tree",
    "ras": "Capricorn",
    "gan": "Elephant",
    "phone_number": "9123456789",
    "education": "MBA",
    "demands": "Looking for a supportive partner",
    "job": "Manager",
    "height": "5'6\"",
    "about": "An ambitious and driven individual.",
    "email": "sita.patil@example.com",
    "fathers_name": "Mr. Patil",
    "mothers_name": "Mrs. Patil",
    "family_type": "Joint family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/3.jpeg",
    "video": "",
    "full_name": "Rahul Deshmukh",
    "address": "Pune",
    "age": "28",
    "gender": "male",
    "cast": "Christian",
    "sub_cast": "Roman Catholic",
    "devak": "Mango Tree",
    "ras": "Leo",
    "gan": "Tiger",
    "phone_number": "9234567890",
    "education": "B.Tech",
    "demands": "Seeking a partner with similar values",
    "job": "Software Engineer",
    "height": "5'10\"",
    "about": "A tech-savvy and innovative thinker.",
    "email": "rahul.deshmukh@example.com",
    "fathers_name": "Mr. Deshmukh",
    "mothers_name": "Mrs. Deshmukh",
    "family_type": "Nuclear family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/4.jpeg",
    "video": "",
    "full_name": "Priya Joshi",
    "address": "Mumbai",
    "age": "27",
    "gender": "female",
    "cast": "Muslim",
    "sub_cast": "Sunni",
    "devak": "Peepal Tree",
    "ras": "Aquarius",
    "gan": "Deer",
    "phone_number": "9345678901",
    "education": "B.Com",
    "demands": "Looking for a caring and loving partner",
    "job": "Teacher",
    "height": "5'5\"",
    "about": "A passionate educator and a loving friend.",
    "email": "priya.joshi@example.com",
    "fathers_name": "Mr. Joshi",
    "mothers_name": "Mrs. Joshi",
    "family_type": "Joint family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg",
    "video": "",
    "full_name": "Anita Singh",
    "address": "Delhi",
    "age": "24",
    "gender": "female",
    "cast": "Sikh",
    "sub_cast": "Jatt",
    "devak": "Neem Tree",
    "ras": "Pisces",
    "gan": "Horse",
    "phone_number": "9456789012",
    "education": "MA in English",
    "demands": "Seeking an educated and understanding partner",
    "job": "Writer",
    "height": "5'3\"",
    "about": "An avid reader and a creative writer.",
    "email": "anita.singh@example.com",
    "fathers_name": "Mr. Singh",
    "mothers_name": "Mrs. Singh",
    "family_type": "Nuclear family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/6.jpeg",
    "video": "",
    "full_name": "Vikram Yadav",
    "address": "Indore",
    "age": "30",
    "gender": "male",
    "cast": "Hindu",
    "sub_cast": "Yadav",
    "devak": "Bamboo Tree",
    "ras": "Gemini",
    "gan": "Falcon",
    "phone_number": "9567890123",
    "education": "BBA",
    "demands": "Looking for a fun-loving partner",
    "job": "Entrepreneur",
    "height": "6'0\"",
    "about": "A dynamic entrepreneur with big dreams.",
    "email": "vikram.yadav@example.com",
    "fathers_name": "Mr. Yadav",
    "mothers_name": "Mrs. Yadav",
    "family_type": "Joint family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/7.jpeg",
    "video": "",
    "full_name": "Neha Mehta",
    "address": "Ahmedabad",
    "age": "26",
    "gender": "female",
    "cast": "Parsi",
    "sub_cast": "Irani",
    "devak": "Peepal Tree",
    "ras": "Taurus",
    "gan": "Owl",
    "phone_number": "9878901234",
    "education": "M.Sc",
    "demands": "Seeking a responsible and loving partner",
    "job": "Researcher",
    "height": "5'7\"",
    "about": "A dedicated researcher with a curious mind.",
    "email": "neha.mehta@example.com",
    "fathers_name": "Mr. Mehta",
    "mothers_name": "Mrs. Mehta",
    "family_type": "Nuclear family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/8.jpeg",
    "video": "",
    "full_name": "Ajay Sharma",
    "address": "Bhopal",
    "age": "29",
    "gender": "male",
    "cast": "Hindu",
    "sub_cast": "Brahmin",
    "devak": "Coconut Tree",
    "ras": "Virgo",
    "gan": "Tiger",
    "phone_number": "8765432109",
    "education": "MCA",
    "demands": "Looking for a partner with a great sense of humor",
    "job": "IT Consultant",
    "height": "5'11\"",
    "about": "A tech enthusiast and a great friend.",
    "email": "ajay.sharma@example.com",
    "fathers_name": "Mr. Sharma",
    "mothers_name": "Mrs. Sharma",
    "family_type": "Joint family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/9.jpeg",
    "video": "",
    "full_name": "Riya Soni",
    "address": "Surat",
    "age": "23",
    "gender": "female",
    "cast": "Christian",
    "sub_cast": "Protestant",
    "devak": "Bamboo Tree",
    "ras": "Libra",
    "gan": "Peacock",
    "phone_number": "8901234567",
    "education": "B.Sc",
    "demands": "Seeking a creative and open-minded partner",
    "job": "Graphic Designer",
    "height": "5'4\"",
    "about": "A creative soul with a love for design.",
    "email": "riya.soni@example.com",
    "fathers_name": "Mr. Soni",
    "mothers_name": "Mrs. Soni",
    "family_type": "Nuclear family"
  },
  {
    "image_url": "https://rn53themes.net/themes/matrimo/images/profiles/10.jpeg",
    "video": "",
    "full_name": "Karan Patel",
    "address": "Vadodara",
    "age": "31",
    "gender": "male",
    "cast": "Hindu",
    "sub_cast": "Patel",
    "devak": "Neem Tree",
    "ras": "Scorpio",
    "gan": "Wolf",
    "phone_number": "7654321098",
    "education": "B.E.",
    "demands": "Looking for a partner with similar interests",
    "job": "Civil Engineer",
    "height": "5'9\"",
    "about": "An outdoor enthusiast who loves adventure.",
    "email": "karan.patel@example.com",
    "fathers_name": "Mr. Patel",
    "mothers_name": "Mrs. Patel",
    "family_type": "Joint family"
  }
  // Continue adding the next 10 users similarly
];
