final List<Map<String, dynamic>> userList = [
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/3.jpg',
    'video': 'https://example.com/video1.mp4',
    'full_name': 'Julia Ann',
    'address': 'New York',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Maratha',
    'devak': 'Lotus',
    'ras': 'Leo',
    'gan': 'Dog',
    'phone_number': '1234567890',
    'education': 'B.Tech (CSE)',
    'demands': 'Looking for a well-settled partner',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men1.jpg',
    'video': '',
    'full_name': 'John Doe',
    'address': 'San Francisco',
    'age': '28',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Oak Tree',
    'ras': 'Taurus',
    'gan': 'Elephant',
    'phone_number': '0987654321',
    'education': 'M.S. (Mechanical Engineering)',
    'demands': 'Looking for a well-settled partner',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/4.jpg',
    'video': 'https://example.com/video2.mp4',
    'full_name': 'Sophia Brown',
    'address': 'Los Angeles',
    'age': '25',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Sunni',
    'devak': 'Moon',
    'ras': 'Gemini',
    'gan': 'Horse',
    'phone_number': '2345678901',
    'education': 'B.A. (English)',
    'demands': 'Seeking a partner who values family',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/men4.jpg',
    'video': '',
    'full_name': 'Michael Smith',
    'address': 'Chicago',
    'age': '30',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Brahmin',
    'devak': 'Peepal Tree',
    'ras': 'Aries',
    'gan': 'Lion',
    'phone_number': '3456789012',
    'education': 'PhD (Physics)',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Emma Johnson',
    'address': 'Houston',
    'age': '24',
    'gender': 'female',
    'cast': 'Christian',
    'sub_cast': 'Protestant',
    'devak': 'Rose',
    'ras': 'Cancer',
    'gan': 'Swan',
    'phone_number': '4567890123',
    'education': 'B.Sc (Biology)',
    'demands': 'Prefers a partner who loves nature',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video3.mp4',
    'full_name': 'Ava Williams',
    'address': 'Phoenix',
    'age': '27',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Vaishya',
    'devak': 'Sunflower',
    'ras': 'Leo',
    'gan': 'Tiger',
    'phone_number': '5678901234',
    'education': 'MBA',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'James Wilson',
    'address': 'Philadelphia',
    'age': '29',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Kshatriya',
    'devak': 'Lion',
    'ras': 'Virgo',
    'gan': 'Elephant',
    'phone_number': '6789012345',
    'education': 'B.Tech (Civil Engineering)',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video4.mp4',
    'full_name': 'Isabella Martinez',
    'address': 'San Antonio',
    'age': '23',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Shia',
    'devak': 'Star',
    'ras': 'Libra',
    'gan': 'Peacock',
    'phone_number': '7890123456',
    'education': 'BBA',
    'demands': 'Looking for a partner who is understanding',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Elijah Anderson',
    'address': 'San Diego',
    'age': '26',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Olive Tree',
    'ras': 'Scorpio',
    'gan': 'Bear',
    'phone_number': '8901234567',
    'education': 'M.S. (Computer Science)',
    'demands': 'Open to relocating for the right partner',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Mia Thomas',
    'address': 'Dallas',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Shudra',
    'devak': 'Lotus',
    'ras': 'Sagittarius',
    'gan': 'Dog',
    'phone_number': '9012345678',
    'education': 'B.Com',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video5.mp4',
    'full_name': 'Noah Lee',
    'address': 'San Jose',
    'age': '31',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Protestant',
    'devak': 'Tulip',
    'ras': 'Capricorn',
    'gan': 'Monkey',
    'phone_number': '0123456789',
    'education': 'M.A. (History)',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Liam Harris',
    'address': 'Austin',
    'age': '27',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Maratha',
    'devak': 'Mango Tree',
    'ras': 'Aquarius',
    'gan': 'Lion',
    'phone_number': '1234567891',
    'education': 'B.Tech (IT)',
    'demands': 'Looking for a partner with similar values',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Olivia Clark',
    'address': 'Jacksonville',
    'age': '24',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Sunni',
    'devak': 'Moon',
    'ras': 'Pisces',
    'gan': 'Fish',
    'phone_number': '2345678902',
    'education': 'B.Sc (Chemistry)',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video6.mp4',
    'full_name': 'William Moore',
    'address': 'Fort Worth',
    'age': '28',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Oak Tree',
    'ras': 'Aries',
    'gan': 'Horse',
    'phone_number': '3456789013',
    'education': 'M.S. (Electrical Engineering)',
    'demands': 'Looking for a partner who is career-oriented',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Henry Davis',
    'address': 'Columbus',
    'age': '29',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Vaishya',
    'devak': 'Rose',
    'ras': 'Taurus',
    'gan': 'Peacock',
    'phone_number': '4567890124',
    'education': 'MBA',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': 'https://example.com/video7.mp4',
    'full_name': 'Ella Martin',
    'address': 'Charlotte',
    'age': '23',
    'gender': 'female',
    'cast': 'Christian',
    'sub_cast': 'Protestant',
    'devak': 'Tulip',
    'ras': 'Gemini',
    'gan': 'Dog',
    'phone_number': '5678901235',
    'education': 'BBA',
    'demands': 'Looking for a partner who enjoys traveling',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Emily Thompson',
    'address': 'San Francisco',
    'age': '26',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Brahmin',
    'devak': 'Peepal Tree',
    'ras': 'Cancer',
    'gan': 'Swan',
    'phone_number': '6789012346',
    'education': 'PhD (Mathematics)',
    'demands': '',
  },
  {
    'image_url': 'https://rn53themes.net/themes/matrimo/images/profiles/5.jpeg',
    'video': '',
    'full_name': 'Benjamin Garcia',
    'address': 'Indianapolis',
    'age': '25',
    'gender': 'male',
    'cast': 'Muslim',
    'sub_cast': 'Shia',
    'devak': 'Star',
    'ras': 'Leo',
    'gan': 'Bear',
    'phone_number': '7890123457',
    'education': 'M.A. (Political Science)',
    'demands': 'Looking for a partner with strong family values',
  },
  {
    'image_url': 'https://randomuser.me/api/portraits/men/6.jpg',
    'video': 'https://example.com/video8.mp4',
    'full_name': 'Lucas Perez',
    'address': 'San Antonio',
    'age': '30',
    'gender': 'male',
    'cast': 'Christian',
    'sub_cast': 'Catholic',
    'devak': 'Sunflower',
    'ras': 'Virgo',
    'gan': 'Elephant',
    'phone_number': '8901234568',
    'education': 'B.A. (History)',
    'demands': '',
  },
  {
    'image_url': 'https://randomuser.me/api/portraits/women/6.jpg',
    'video': '',
    'full_name': 'Charlotte Hall',
    'address': 'Denver',
    'age': '22',
    'gender': 'female',
    'cast': 'Hindu',
    'sub_cast': 'Shudra',
    'devak': 'Lotus',
    'ras': 'Libra',
    'gan': 'Peacock',
    'phone_number': '9012345679',
    'education': 'B.Com',
    'demands': '',
  },
  {
    'image_url': '',
    'video': '',
    'full_name': 'Amelia Young',
    'address': 'Boston',
    'age': '24',
    'gender': 'female',
    'cast': 'Muslim',
    'sub_cast': 'Sunni',
    'devak': 'Moon',
    'ras': 'Scorpio',
    'gan': 'Fish',
    'phone_number': '0123456781',
    'education': 'B.Sc (Physics)',
    'demands': 'Looking for a partner who values education',
  },
  {
    'image_url': 'https://randomuser.me/api/portraits/men/7.jpg',
    'video': '',
    'full_name': 'Mason King',
    'address': 'Detroit',
    'age': '29',
    'gender': 'male',
    'cast': 'Hindu',
    'sub_cast': 'Maratha',
    'devak': 'Mango Tree',
    'ras': 'Sagittarius',
    'gan': 'Tiger',
    'phone_number': '1234567892',
    'education': 'B.Tech (Electronics)',
    'demands': '',
  }
];
